## Problem 4.2

In [36]:
# create random matrices and compute their inverses
import numpy as np

a = np.random.randint(-10, 11, size=(3, 3))
b = np.random.randint(-10, 11, size=(3, 3))
c = np.random.randint(-10, 11, size=(3, 3))

print("a and a inverse:")
print(a, "\n\n", np.linalg.inv(a), "\n")
print("b and b inverse:")
print(b, "\n\n", np.linalg.inv(b), "\n")
print("c and c inverse:")
print(c, "\n\n", np.linalg.inv(c), "\n")

a and a inverse:
[[ -9   9   2]
 [  1  10  -1]
 [  1   0 -10]] 

 [[-0.10405827  0.09365245 -0.0301769 ]
 [ 0.00936524  0.09157128 -0.00728408]
 [-0.01040583  0.00936524 -0.10301769]] 

b and b inverse:
[[-7 -6  2]
 [ 9  0  4]
 [ 9 -7  1]] 

 [[-0.05785124  0.01652893  0.04958678]
 [-0.05578512  0.05165289 -0.09504132]
 [ 0.13016529  0.21280992 -0.11157025]] 

c and c inverse:
[[-3  5  1]
 [ 7 -7 -7]
 [-1  1  0]] 

 [[ 5.00000000e-01  7.14285714e-02 -2.00000000e+00]
 [ 5.00000000e-01  7.14285714e-02 -1.00000000e+00]
 [ 2.77555756e-17 -1.42857143e-01 -1.00000000e+00]] 



In [37]:
print("Verification (matrix * inverse = identity):")
print("a * a_inv:")
print(np.matmul(a, np.linalg.inv(a)))
print("b * b_inv:")
print(np.matmul(b, np.linalg.inv(b)))
print("c * c_inv:")
print(np.matmul(c, np.linalg.inv(c)))

Verification (matrix * inverse = identity):
a * a_inv:
[[ 1.00000000e+00 -5.89805982e-17  0.00000000e+00]
 [-3.46944695e-18  1.00000000e+00  0.00000000e+00]
 [-1.38777878e-17  1.73472348e-17  1.00000000e+00]]
b * b_inv:
[[ 1.00000000e+00  1.11022302e-16 -8.32667268e-17]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-2.77555756e-17  0.00000000e+00  1.00000000e+00]]
c * c_inv:
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.94289029e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


## Problem 5

In [38]:
# For each feature, write code to compute the average value, the min and max values, as well as its variance.

import pandas as pd

df = pd.read_csv('kc_house_data.csv')
df.drop(columns=['id', 'date', 'zipcode'], inplace=True)

price = df['price']
bedrooms = df['bedrooms']
bathrooms = df['bathrooms']
sqft_living = df['sqft_living']
sqft_lot = df['sqft_lot']
floors = df['floors']
waterfront = df['waterfront']
view = df['view']
condition = df['condition']
grade = df['grade']
sqft_above = df['sqft_above']
sqft_basement = df['sqft_basement']
yr_built = df['yr_built']
yr_renovated = df['yr_renovated']
lat = df['lat']
long = df['long']
sqft_living15 = df['sqft_living15']
sqft_lot15 = df['sqft_lot15']

features = [price, bedrooms, bathrooms, sqft_living, sqft_lot, floors, waterfront, view, condition, grade, sqft_above, sqft_basement, yr_built, yr_renovated, lat, long, sqft_living15, sqft_lot15]


for feature in features:
    print(f"Feature: {feature.name}")
    print(f"Average: {feature.mean()}")
    print(f"Min: {feature.min()}")
    print(f"Max: {feature.max()}")
    print(f"Variance: {feature.var()}\n")

Feature: price
Average: 540088.1417665294
Min: 75000.0
Max: 7700000.0
Variance: 134782378397.24687

Feature: bedrooms
Average: 3.37084162309721
Min: 0
Max: 33
Variance: 0.8650150097573508

Feature: bathrooms
Average: 2.1147573219821405
Min: 0.0
Max: 8.0
Variance: 0.5931512887356003

Feature: sqft_living
Average: 2079.8997362698374
Min: 290
Max: 13540
Variance: 843533.6813681518

Feature: sqft_lot
Average: 15106.967565816869
Min: 520
Max: 1651359
Variance: 1715658774.1754704

Feature: floors
Average: 1.4943089807060566
Min: 1.0
Max: 3.5
Variance: 0.29158800687705183

Feature: waterfront
Average: 0.007541757275713691
Min: 0
Max: 1
Variance: 0.007485225502686407

Feature: view
Average: 0.23430342849211122
Min: 0
Max: 4
Variance: 0.5872426169774174

Feature: condition
Average: 3.4094295100171195
Min: 1
Max: 5
Variance: 0.4234665123939715

Feature: grade
Average: 7.656873178179799
Min: 1
Max: 13
Variance: 1.3817032893476489

Feature: sqft_above
Average: 1788.3906907879516
Min: 290
Max: 9410

In [39]:
# Compute the correlation coefficient of each feature with the response. 
# Include a table with the correlation coefficient of each feature with the response. 

correlations = df.corrwith(df['price'])
print(correlations)

price            1.000000
bedrooms         0.308350
bathrooms        0.525138
sqft_living      0.702035
sqft_lot         0.089661
floors           0.256794
waterfront       0.266369
view             0.397293
condition        0.036362
grade            0.667434
sqft_above       0.605567
sqft_basement    0.323816
yr_built         0.054012
yr_renovated     0.126434
lat              0.307003
long             0.021626
sqft_living15    0.585379
sqft_lot15       0.082447
dtype: float64
