In [3]:
import numpy as np

a = np.array([[1, 7, 3], [9, 2, 5], [1, -4, 8]])
b = np.array([[2, 5, 9], [-1, -8, 0], [3, 7, 6]])
c = np.array([[9, 3, -4], [10, -7, 8], [1, 5, 2]])

print("a inverse:")
print(np.linalg.inv(a))
print("b inverse:")
print(np.linalg.inv(b))
print("c inverse:")
print(np.linalg.inv(c))



a inverse:
[[-0.06581353  0.12431444 -0.05301645]
 [ 0.12248629 -0.00914077 -0.04021938]
 [ 0.06946984 -0.02010969  0.11151737]]
b inverse:
[[-0.55172414  0.37931034  0.82758621]
 [ 0.06896552 -0.17241379 -0.10344828]
 [ 0.1954023   0.01149425 -0.12643678]]
c inverse:
[[ 0.072       0.03466667  0.00533333]
 [ 0.016      -0.02933333  0.14933333]
 [-0.076       0.056       0.124     ]]


In [2]:
print("\nVerification (matrix * inverse = identity):")
print("a * a_inv:")
print(np.matmul(a, np.linalg.inv(a)))
print("b * b_inv:")
print(np.matmul(b, np.linalg.inv(b)))
print("c * c_inv:")
print(np.matmul(c, np.linalg.inv(c)))


Verification (matrix * inverse = identity):
a * a_inv:
[[ 1.00000000e+00 -6.93889390e-18  0.00000000e+00]
 [ 1.38777878e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
b * b_inv:
[[ 1.00000000e+00 -6.93889390e-18 -2.77555756e-17]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.38777878e-17  1.00000000e+00]]
c * c_inv:
[[ 1.00000000e+00  2.77555756e-17 -1.66533454e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 2.77555756e-17 -1.38777878e-17  1.00000000e+00]]
